
package tuning.profview;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class ProfileCallerAggregate
{
	int time;
	int count;
	ProfileMethod caller;

/**
 * This method was created by a SmartGuide.
 * @param callee jack.profiler.ProfileMethod
 */
public ProfileCallerAggregate(ProfileLine line)
{
	count = line.count;
	time = line.time;
	caller = line.caller;
}
/**
 * This method was created by a SmartGuide.
 */
public void add(ProfileLine line)
{
	count += line.count;
	time += line.time;
}
/**
 * This method was created by a SmartGuide.
 * @param s java.lang.StringBuffer
 */
public void appendTo(StringBuffer s, boolean timeFirst)
{
	s.append(timeFirst ? time : count).append("\t").append(timeFirst ? count : time).append("\t");
	caller.appendTo(s);
}
}