package hjapp.com.umeng.fb;

public class f
{
  public static final String A = "UmengFb_Nums";
  public static final String B = "newReplyIds";
  public static final String C = "maxReplyID";
  public static final String D = "email";
  public static final String E = "ageGroup";
  public static final String F = "sex";
  public static final String G = "OtherAttrContext";
  public static final String H = "OtherAttrRemark";
  public static final String I = "Json_OtherAttrContact";
  public static final String J = "Json_OtherAttrRemark";
  public static final String K = "contact";
  public static final String L = "remark";
  public static final String M = "umeng_reply_index";
  static final String N = "age";
  static final String O = "gender";
  static final String P = "user_id";
  static final String Q = "id_source";
  static final String R = "traffics";
  public static final String S = "content";
  public static final String T = "thread";
  public static final String U = "datetime";
  public static final String V = "user_id";
  public static final String W = "feedback_id";
  public static final String X = "reply_id";
  public static final String Y = "age_group";
  public static final String Z = "gender";
  public static final String a = "Android";
  public static final String aA = "RetrieveReplyBroadcast";
  public static final int aB = -1;
  public static final int aC = 1;
  public static final int aD = 0;
  public static final String aE = "HasNewReplyBroadcast";
  public static final int aF = 1;
  public static final int aG = 0;
  public static final String aH = "postFeedbackFinished";
  public static final String aI = "NewReplyNotifyType";
  public static final int aJ = 1;
  public static final int aK = 0;
  public static final String aL = "NewReplyContent";
  public static final String aM = "umeng_local_report_policy";
  public static final String aN = "umeng_net_report_policy";
  public static final String aO = "umeng_last_config_time";
  public static final String aP = "umeng_last_update_time";
  public static final String aQ = "umeng_update_internal";
  public static final String aa = "other";
  public static final String ab = "email";
  public static final String ac = "appkey";
  public static final String ad = "reply_id";
  public static final String ae = "lat";
  public static final String af = "lng";
  public static final String ag = "msg";
  public static final String ah = "sdk_version";
  public static final String ai = "app_version";
  public static final String aj = "os_version";
  public static final String ak = "device_model";
  public static final String al = "reply_id";
  public static final String am = "state";
  public static final String an = "error";
  public static final String ao = "ok";
  public static final String ap = "type";
  public static final String aq = "user_reply";
  public static final String ar = "new_feedback";
  public static final String as = "dev_reply";
  public static final String at = "responce";
  public static final String au = "fail";
  public static final String av = "sending";
  public static final String aw = "ok";
  public static final String ax = "PostFeedbackBroadcast";
  public static final String ay = "fail";
  public static final String az = "succeed";
  public static final String b = "Android";
  public static final String c = "4.1.0.20120709";
  public static long d = 0L;
  public static boolean e = false;
  public static final int f = 8;
  static final int g = 10;
  public static boolean h = false;
  public static boolean i = false;
  public static boolean j = false;
  public static boolean k = false;
  public static boolean l = false;
  public static String m = null;
  public static String n = "last_send_time";
  public static final Object o = new Object();
  public static final String p = "MobclickAgent";
  public static final String[] q = { "http://www.umeng.com/app_logs", "http://www.umeng.co/app_logs" };
  public static final String[] r = { "http://www.umeng.com/api/check_app_update", "http://www.umeng.co/api/check_app_update" };
  public static final String s = "http://www.umeng.com/check_config_update";
  public static final String t = "http://www.umeng.co/check_config_update";
  public static boolean u = false;
  public static final String v = "http://feedback.whalecloud.com/feedback";
  public static final String w = "http://feedback.whalecloud.com/feedback/reply";
  public static final String x = "http://feedback.whalecloud.com/feedback/reply";
  public static final String y = "http://feedback.whalecloud.com/feedback/feedbacks";
  public static final String z = "feedback";
}

/* Location:           D:\tmp\沪江课件专用播放器\反编译工具包\jd-gui-0.3.5.windows\classes_dex2jar.jar
 * Qualified Name:     f
 * JD-Core Version:    0.6.2
 */