package tuning.distrib.corba;


/**
* tuning/distrib/corba/ServerObject.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from tuning/distrib/corba/ServerObject.idl
* Thursday, March 23, 2000 7:10:51 PM GMT+00:00
*/

public interface ServerObject extends ServerObjectOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObject
