package tuning.distrib.corba;

/**
* tuning/distrib/corba/ServerObjectHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from tuning/distrib/corba/ServerObject.idl
* Thursday, March 23, 2000 7:10:51 PM GMT+00:00
*/

public final class ServerObjectHolder implements org.omg.CORBA.portable.Streamable
{
  public tuning.distrib.corba.ServerObject value = null;

  public ServerObjectHolder ()
  {
  }

  public ServerObjectHolder (tuning.distrib.corba.ServerObject initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tuning.distrib.corba.ServerObjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tuning.distrib.corba.ServerObjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tuning.distrib.corba.ServerObjectHelper.type ();
  }

}
