package tuning.distrib.corba;


/**
* tuning/distrib/corba/ServerObjectOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from tuning/distrib/corba/ServerObject.idl
* Thursday, March 23, 2000 7:10:51 PM GMT+00:00
*/

public interface ServerObjectOperations 
{
  boolean getBoolean ();
  int getNumber ();
  String getString ();
  void setBoolean (boolean flag);
  void setNumber (int i);
  void setString (String obj);
  void setAll (boolean flag, int i, String obj);
} // interface ServerObjectOperations
