
package hellowebservice;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6hudson-86 
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "HelloWSPort", serviceName = "HelloWSService", targetNamespace = "http://hellowebservice/", wsdlLocation = "/wsdls/HelloWSService.wsdl", endpointInterface = "hellowebservice.HelloWS")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class HelloWSService_HelloWSPortImpl
    implements HelloWS
{


    public HelloWSService_HelloWSPortImpl() {
    }

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    public String hello(String arg0) {
        //replace with your impl here
        return null;
    }

}
